# Seyed Ali Mirferdos
# 99201465

# 1. Importing required modules

In [32]:
import numpy as np

# 2. The CUR function

In [125]:
def cur(data, chosen_cols, chosen_rows):
  r = len(chosen_cols)
  total_M = np.sum(data**2)

  C_vals = data[:, chosen_cols]
  print(f"C:\n{C_vals}")
  C_M = np.sum(data**2, axis=0) / total_M
  C = C_vals / np.sqrt(r * C_M[chosen_cols])
  print(f"C Scaled:\n{C}")

  R_vals = data[chosen_rows, :].T
  print(f"R:\n{R_vals}")
  R_M = np.sum(data**2, axis=1) / total_M
  R = R_vals / np.sqrt(r * R_M[chosen_rows])
  print(f"R Scaled:\n{R_vals}")

  W = np.array([[1, 0, 0],
                [1, 0, 0],
                [0, 1, 1]])
  print(f"W:\n{W}")
  X, S, Yt = np.linalg.svd(W)
  print(f"Sigma:\n{S}")
  pS = np.divide(1, S, out=np.zeros_like(S), where=(S!=0))
  print(f"Inverse Sigma:\n{pS}")
  U = Yt.T @ np.diag(pS ** 2) @ X.T

  return C, U, R.T

# 3. Executing the function on the given matrix

In [118]:
data = np.array([[1, 1, 0, 0, 0],
                 [0, 1, 0, 0, 1],
                 [0, 0, 1, 0, 1],
                 [0, 0, 1, 1, 1]])

In [119]:
chosen_cols = [0, 2, 4]
chosen_rows = [0, 0, 2]

In [126]:
C, U, R = cur(data, chosen_cols, chosen_rows)

C:
[[1 0 0]
 [0 0 1]
 [0 1 1]
 [0 1 1]]
C Scaled:
[[1.73205081 0.         0.        ]
 [0.         0.         1.        ]
 [0.         1.22474487 1.        ]
 [0.         1.22474487 1.        ]]
R:
[[1 1 0]
 [1 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 1]]
R Scaled:
[[1 1 0]
 [1 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 1]]
W:
[[1 0 0]
 [1 0 0]
 [0 1 1]]
Sigma:
[1.41421356 1.41421356 0.        ]
Inverse Sigma:
[0.70710678 0.70710678 0.        ]


In [123]:
print('C: \n', C)
print('U: \n', U)
print('R: \n', R)

C: 
 [[1.73205081 0.         0.        ]
 [0.         0.         1.        ]
 [0.         1.22474487 1.        ]
 [0.         1.22474487 1.        ]]
U: 
 [[0.35355339 0.35355339 0.        ]
 [0.         0.         0.35355339]
 [0.         0.         0.35355339]]
R: 
 [[1.22474487 1.22474487 0.         0.         0.        ]
 [1.22474487 1.22474487 0.         0.         0.        ]
 [0.         0.         1.22474487 0.         1.22474487]]


In [124]:
C @ U @ R

array([[1.5       , 1.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.4330127 , 0.        , 0.4330127 ],
       [0.        , 0.        , 0.96334279, 0.        , 0.96334279],
       [0.        , 0.        , 0.96334279, 0.        , 0.96334279]])