### Q1

In [1]:
import networkx as nx
import numpy as np

A = np.array([[0, 1, 1, 1, 1], 
              [1, 0, 1, 1, 1], 
              [1, 1, 0, 1, 1], 
              [1, 1, 1, 0, 1],
              [0, 0, 0, 0, 0]])

h = np.ones((5))
a = np.ones((5))

In [ ]:
(A.T@A)@[0.75, 0.75, 0.75, 0.75, 1]

array([ 9.75,  9.75,  9.75,  9.75, 13.  ])

In [ ]:
M_hub = A@A.T
for i in range(10):
    h = M_hub@h
    h = h/np.max(h)
    print(h)

[1. 1. 1. 1. 0.]
[1. 1. 1. 1. 0.]
[1. 1. 1. 1. 0.]
[1. 1. 1. 1. 0.]
[1. 1. 1. 1. 0.]
[1. 1. 1. 1. 0.]
[1. 1. 1. 1. 0.]
[1. 1. 1. 1. 0.]
[1. 1. 1. 1. 0.]
[1. 1. 1. 1. 0.]


In [ ]:
M_aut = A.T@A
for i in range(10):
    a = M_aut@a
    a = a/np.max(a)
    print(a)

[0.75 0.75 0.75 0.75 1.  ]
[0.75 0.75 0.75 0.75 1.  ]
[0.75 0.75 0.75 0.75 1.  ]
[0.75 0.75 0.75 0.75 1.  ]
[0.75 0.75 0.75 0.75 1.  ]
[0.75 0.75 0.75 0.75 1.  ]
[0.75 0.75 0.75 0.75 1.  ]
[0.75 0.75 0.75 0.75 1.  ]
[0.75 0.75 0.75 0.75 1.  ]
[0.75 0.75 0.75 0.75 1.  ]


In [ ]:
import networkx as nx
G = nx.from_numpy_matrix(A)
G = nx.DiGraph()
for i in range(len(A)):
    for j in range(len(A)):
        if(A[i][j]==1):
            G.add_edges_from([(i,j)])


hubs, authorities = nx.hits(G, max_iter = 50, normalized = True)
print(hubs)
print(authorities)

{0: 0.25, 1: 0.25, 2: 0.25, 3: 0.25, 4: 0.0}
{0: 0.1875, 1: 0.1875, 2: 0.1875, 3: 0.1875, 4: 0.25}


# PageRank

In [32]:
M = np.array([[0,    0.25, 0.25, 0.25, 0], 
              [0.25, 0,    0.25, 0.25, 0], 
              [0.25, 0.25, 0,    0.25, 0], 
              [0.25, 0.25, 0.25, 0,    0], 
              [0.25, 0.25, 0.25, 0.25, 0]])

u = [1, 1, 1, 1, 1]
for i in range(50):
  print(f"v{i+1} = {u}")
  u = M@u*0.8+[0, 0, 0, 0.04, 0]

v1 = [1, 1, 1, 1, 1]
v2 = [0.6  0.6  0.6  0.64 0.8 ]
v3 = [0.368 0.368 0.368 0.4   0.488]
v4 = [0.2272 0.2272 0.2272 0.2608 0.3008]
v5 = [0.14304 0.14304 0.14304 0.17632 0.18848]
v6 = [0.09248  0.09248  0.09248  0.125824 0.121088]
v7 = [0.0621568 0.0621568 0.0621568 0.095488  0.0806528]
v8 = [0.04396032 0.04396032 0.04396032 0.07729408 0.05639168]
v9 = [0.03304294 0.03304294 0.03304294 0.06637619 0.04183501]
v10 = [0.02649242 0.02649242 0.02649242 0.05982577 0.033101  ]
v11 = [0.02256212 0.02256212 0.02256212 0.05589545 0.0278606 ]
v12 = [0.02020394 0.02020394 0.02020394 0.05353727 0.02471636]
v13 = [0.01878903 0.01878903 0.01878903 0.05212236 0.02282982]
v14 = [0.01794008 0.01794008 0.01794008 0.05127342 0.02169789]
v15 = [0.01743072 0.01743072 0.01743072 0.05076405 0.02101873]
v16 = [0.0171251  0.0171251  0.0171251  0.05045843 0.02061124]
v17 = [0.01694172 0.01694172 0.01694172 0.05027506 0.02036674]
v18 = [0.0168317  0.0168317  0.0168317  0.05016503 0.02022005]
v19 = [0.01676569 0.0

In [38]:
v = (u/u.sum())

In [40]:
p=[0.19,  0.19,  0.19,  0.19,  0.23]
(p-v)/p

array([ 0.26900585,  0.26900585,  0.26900585, -1.19298246,  0.27536232])

In [22]:
A = np.array([[1,  0,  0,  0,  0,  0], 
       [0,  1,  0,  0,  0,  0,] ,
       [0,  0,  1,  0,  0,  0,] ,
       [1,  1,  1,  1,  0,  0,] ,
       [1,  1,  1,  0,  1,  0,] ,
       [1,  1,  1,  0,  0,  1]])
G = nx.from_numpy_matrix(A)
nx.pagerank(G)


{0: 0.16666666666666663,
 1: 0.16666666666666663,
 2: 0.16666666666666663,
 3: 0.16666666666666666,
 4: 0.16666666666666666,
 5: 0.16666666666666666}

In [25]:
A = np.array([[0,    0.25, 0.25, 0.25, 0], 
              [0.25, 0,    0.25, 0.25, 0], 
              [0.25, 0.25, 0,    0.25, 0], 
              [0.25, 0.25, 0.25, 0,    0], 
              [0.25, 0.25, 0.25, 0.25, 0]])
G = nx.from_numpy_matrix(A)
nx.pagerank_numpy(G)

{0: 0.19999999999999998, 1: 0.2, 2: 0.2, 3: 0.2, 4: 0.2}

In [14]:
G.edges()

EdgeView([(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)])

In [11]:
pr

{0: 0.20000000000000004,
 1: 0.20000000000000004,
 2: 0.20000000000000004,
 3: 0.2,
 4: 0.2}

In [ ]:
4*0.1875

0.75

In [ ]:
import networkx as nx
import numpy as np

G = nx.DiGraph()
G.add_edges_from([(1,1),(1,2),(1,3)])
G.add_edges_from([(2,4),(2,5)])
G.add_edges_from([(3,6),(3,7)])
G.add_edges_from([(4,8),(4,9)])
G.add_edges_from([(5,10),(5,11)])
G.add_edges_from([(6,12),(6,13)])
G.add_edges_from([(7,14),(7,15)])

cnt = 16
for i in range(8,16):
    for j in range(2):
        G.add_edges_from([(i,cnt)])
        cnt+=1
        
hubs, authorities = nx.hits(G, max_iter = 100, normalized = True)
print(hubs)
print(authorities)                        

{1: 0.9999999853622679, 2: 1.0455523483514544e-09, 3: 1.0455523483514544e-09, 4: 1.0455523483514544e-09, 5: 1.0455523483514544e-09, 6: 1.0455523483514544e-09, 7: 1.0455523483514544e-09, 8: 1.0455523483514544e-09, 9: 1.0455523483514544e-09, 10: 1.0455523483514544e-09, 11: 1.0455523483514544e-09, 12: 1.0455523483514544e-09, 13: 1.0455523483514544e-09, 14: 1.0455523483514544e-09, 15: 1.0455523483514544e-09, 16: 0.0, 17: 0.0, 18: 0.0, 19: 0.0, 20: 0.0, 21: 0.0, 22: 0.0, 23: 0.0, 24: 0.0, 25: 0.0, 26: 0.0, 27: 0.0, 28: 0.0, 29: 0.0, 30: 0.0, 31: 0.0}
{1: 0.3333333284540889, 2: 0.3333333284540889, 3: 0.3333333284540889, 4: 5.227761741757266e-10, 5: 5.227761741757266e-10, 6: 5.227761741757266e-10, 7: 5.227761741757266e-10, 8: 5.227761741757266e-10, 9: 5.227761741757266e-10, 10: 5.227761741757266e-10, 11: 5.227761741757266e-10, 12: 5.227761741757266e-10, 13: 5.227761741757266e-10, 14: 5.227761741757266e-10, 15: 5.227761741757266e-10, 16: 5.227761741757266e-10, 17: 5.227761741757266e-10, 18: 5.

### Q2

In [ ]:
V = np.array([1,1,1,1,1,1])

for i in range(20):
    V = M.dot(V)
    print(V)

[0.25 0.25 0.25 1.75 1.75 1.75]
[0.0625 0.0625 0.0625 1.9375 1.9375 1.9375]
[0.015625 0.015625 0.015625 1.984375 1.984375 1.984375]
[0.00390625 0.00390625 0.00390625 1.99609375 1.99609375 1.99609375]
[9.76562500e-04 9.76562500e-04 9.76562500e-04 1.99902344e+00
 1.99902344e+00 1.99902344e+00]
[2.44140625e-04 2.44140625e-04 2.44140625e-04 1.99975586e+00
 1.99975586e+00 1.99975586e+00]
[6.10351562e-05 6.10351562e-05 6.10351562e-05 1.99993896e+00
 1.99993896e+00 1.99993896e+00]
[1.52587891e-05 1.52587891e-05 1.52587891e-05 1.99998474e+00
 1.99998474e+00 1.99998474e+00]
[3.81469727e-06 3.81469727e-06 3.81469727e-06 1.99999619e+00
 1.99999619e+00 1.99999619e+00]
[9.53674316e-07 9.53674316e-07 9.53674316e-07 1.99999905e+00
 1.99999905e+00 1.99999905e+00]
[2.38418579e-07 2.38418579e-07 2.38418579e-07 1.99999976e+00
 1.99999976e+00 1.99999976e+00]
[5.96046448e-08 5.96046448e-08 5.96046448e-08 1.99999994e+00
 1.99999994e+00 1.99999994e+00]
[1.49011612e-08 1.49011612e-08 1.49011612e-08 1.99999999

### Q3

In [ ]:
V = np.array([1,1,1,1,1,1])

for i in range(20):
    V = 0.5*M.dot(V) + ((0.5*6)/6)*np.array([1,1,1,1,1,1])
    print(V)

[0.625 0.625 0.625 1.375 1.375 1.375]
[0.578125 0.578125 0.578125 1.421875 1.421875 1.421875]
[0.57226562 0.57226562 0.57226562 1.42773438 1.42773438 1.42773438]
[0.5715332 0.5715332 0.5715332 1.4284668 1.4284668 1.4284668]
[0.57144165 0.57144165 0.57144165 1.42855835 1.42855835 1.42855835]
[0.57143021 0.57143021 0.57143021 1.42856979 1.42856979 1.42856979]
[0.57142878 0.57142878 0.57142878 1.42857122 1.42857122 1.42857122]
[0.5714286 0.5714286 0.5714286 1.4285714 1.4285714 1.4285714]
[0.57142857 0.57142857 0.57142857 1.42857143 1.42857143 1.42857143]
[0.57142857 0.57142857 0.57142857 1.42857143 1.42857143 1.42857143]
[0.57142857 0.57142857 0.57142857 1.42857143 1.42857143 1.42857143]
[0.57142857 0.57142857 0.57142857 1.42857143 1.42857143 1.42857143]
[0.57142857 0.57142857 0.57142857 1.42857143 1.42857143 1.42857143]
[0.57142857 0.57142857 0.57142857 1.42857143 1.42857143 1.42857143]
[0.57142857 0.57142857 0.57142857 1.42857143 1.42857143 1.42857143]
[0.57142857 0.57142857 0.57142857 